# Generated by Django 5.0.6 on 2025-12-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanning_enabled', models.BooleanField(default=True)),
                ('min_profit_pct', models.FloatField(default=1.0)),
                ('max_profit_pct', models.FloatField(default=2.5)),
                ('fee_bps', models.FloatField(default=10)),
                ('extra_fee_bps', models.FloatField(default=0)),
                ('slippage_bps', models.FloatField(default=10)),
                ('min_notional_usd', models.FloatField(default=10)),
                ('max_notional_usd', models.FloatField(default=10000)),
                ('base_asset', models.CharField(default='USDT', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_a', models.CharField(max_length=20)),
                ('leg_b', models.CharField(max_length=20)),
                ('leg_c', models.CharField(max_length=20)),
                ('profit_pct', models.FloatField(default=0)),
                ('volume_usd', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('notional_usd', models.FloatField(default=0)),
                ('pnl_usd', models.FloatField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
        ),
    ]
