# Generated by Django 5.0.6 on 2025-12-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='bot_language',
            field=models.CharField(default='en', max_length=8),
        ),
    ]
