# Generated by Django 5.0.6 on 2026-02-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_botsettings_bot_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='use_entire_balance',
            field=models.BooleanField(default=False),
        ),
    ]
