# Generated by Django 5.0.6 on 2026-03-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_botsettings_auto_trade_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botsettings",
            name="bot_language",
        ),
    ]
